name: {{name.snakeCase()}}
description: {{description.sentenceCase()}}

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  auto_route: ^7.7.0
  bloc: ^8.1.2
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  dio_smart_retry: ^5.0.0
  envied: ^0.3.0+3
  equatable: ^2.0.5
  external_path: ^1.0.3
  {{#usingFirebase}}
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  {{/usingFirebase}}
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  flutter_vibrate: ^1.3.0
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  keyboard_attachable: ^2.1.0
  logger: ^1.4.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  pull_to_refresh: ^2.0.0
  rate_limiter: ^1.0.0
  readmore: ^2.2.0
  recase: ^4.1.0
  share_plus: ^7.0.2

  {{name.snakeCase()}}_ui_kit:
    git:
      url: https://github.com/{{organization.paramCase()}}/{{name.paramCase()}}-ui-kit.git
  slang_flutter: ^3.20.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.12

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  change_app_package_name: ^1.1.0
  envied_generator:
    git:
      url: https://github.com/ryanaidilp/envied.git
      path: packages/envied_generator
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  slang_build_runner: ^3.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true
    rive: false
  line_length: 80

flutter_icons:
  image_path: assets/logo/{{name.snakeCase()}}_icons.png
  android: true
  ios: true
  remove_alpha_ios: true

# Flavor configuration
flavorizr:
  development:
    app:
      name: "(Dev) {{name.titleCase()}}"
      icon: assets/logo/{{name.snakeCase()}}_icons.png
    android:
      applicationId: "com.{{organization.snakeCase()}}.{{name.snakeCase()}}"
    ios:
      bundleId: "com.{{organization.snakeCase()}}.{{name.snakeCase()}}"
  production:
    app:
      name: "{{name.titleCase()}}"
      icon: assets/logo/{{name.snakeCase()}}_icons.png
    android:
      applicationId: "com.{{organization.snakeCase()}}.{{name.snakeCase()}}"
    ios:
      bundleId: "com.{{organization.snakeCase()}}.{{name.snakeCase()}}"
